pipeline {
    agent any
    tools {
         maven 'maven3'
        
    }
    stages{
        stage('Build'){
            steps{
                def pomfilepath= pom.xml /realestate1  
                sh script: 'mvn clean package'
            }
        }
    }
}
