pipeline {
    agent any
    tools {
         maven 'maven3'
         def pomfilepath= <pom.xml /realestate1>
    }
    stages{
        stage('Build'){
            steps{
                  sh script: 'mvn clean package'
            }
        }
    }
}
